// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: ad/v1/ad.proto

package adV1

import (
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAdsRequest) Reset() {
	*x = ListAdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_v1_ad_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsRequest) ProtoMessage() {}

func (x *ListAdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_v1_ad_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsRequest.ProtoReflect.Descriptor instead.
func (*ListAdsRequest) Descriptor() ([]byte, []int) {
	return file_ad_v1_ad_proto_rawDescGZIP(), []int{0}
}

type ListAdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ads []*ListAdsResponse_Ad `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
}

func (x *ListAdsResponse) Reset() {
	*x = ListAdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_v1_ad_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsResponse) ProtoMessage() {}

func (x *ListAdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_v1_ad_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsResponse.ProtoReflect.Descriptor instead.
func (*ListAdsResponse) Descriptor() ([]byte, []int) {
	return file_ad_v1_ad_proto_rawDescGZIP(), []int{1}
}

func (x *ListAdsResponse) GetAds() []*ListAdsResponse_Ad {
	if x != nil {
		return x.Ads
	}
	return nil
}

type ListAdsResponse_Ad struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Уникальный идентификатор
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                          // Заголовок
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`              // Описание
	Category    string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`                    // Категория
	AuthorId    string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`    // ID автор
	Price       *money.Money           `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`                          // Цена
	Status      string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                        // Статус (active, sold, banned)
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания (ISO 8601)
}

func (x *ListAdsResponse_Ad) Reset() {
	*x = ListAdsResponse_Ad{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_v1_ad_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdsResponse_Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsResponse_Ad) ProtoMessage() {}

func (x *ListAdsResponse_Ad) ProtoReflect() protoreflect.Message {
	mi := &file_ad_v1_ad_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsResponse_Ad.ProtoReflect.Descriptor instead.
func (*ListAdsResponse_Ad) Descriptor() ([]byte, []int) {
	return file_ad_v1_ad_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListAdsResponse_Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ListAdsResponse_Ad) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_ad_v1_ad_proto protoreflect.FileDescriptor

var file_ad_v1_ad_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xc3, 0x02, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x61, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x52,
	0x03, 0x61, 0x64, 0x73, 0x1a, 0x82, 0x02, 0x0a, 0x02, 0x41, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x45, 0x0a, 0x09, 0x41, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x73, 0x12, 0x15, 0x2e, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x64, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x42, 0x07, 0x41,
	0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x19, 0x61, 0x64, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61,
	0x64, 0x56, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x05, 0x41, 0x64, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x05, 0x41, 0x64, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x11, 0x41, 0x64, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x06,
	0x41, 0x64, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ad_v1_ad_proto_rawDescOnce sync.Once
	file_ad_v1_ad_proto_rawDescData = file_ad_v1_ad_proto_rawDesc
)

func file_ad_v1_ad_proto_rawDescGZIP() []byte {
	file_ad_v1_ad_proto_rawDescOnce.Do(func() {
		file_ad_v1_ad_proto_rawDescData = protoimpl.X.CompressGZIP(file_ad_v1_ad_proto_rawDescData)
	})
	return file_ad_v1_ad_proto_rawDescData
}

var file_ad_v1_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ad_v1_ad_proto_goTypes = []interface{}{
	(*ListAdsRequest)(nil),        // 0: ad.v1.ListAdsRequest
	(*ListAdsResponse)(nil),       // 1: ad.v1.ListAdsResponse
	(*ListAdsResponse_Ad)(nil),    // 2: ad.v1.ListAdsResponse.Ad
	(*money.Money)(nil),           // 3: google.type.Money
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_ad_v1_ad_proto_depIdxs = []int32{
	2, // 0: ad.v1.ListAdsResponse.ads:type_name -> ad.v1.ListAdsResponse.Ad
	3, // 1: ad.v1.ListAdsResponse.Ad.price:type_name -> google.type.Money
	4, // 2: ad.v1.ListAdsResponse.Ad.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: ad.v1.AdService.ListAds:input_type -> ad.v1.ListAdsRequest
	1, // 4: ad.v1.AdService.ListAds:output_type -> ad.v1.ListAdsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ad_v1_ad_proto_init() }
func file_ad_v1_ad_proto_init() {
	if File_ad_v1_ad_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ad_v1_ad_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_v1_ad_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_v1_ad_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAdsResponse_Ad); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ad_v1_ad_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ad_v1_ad_proto_goTypes,
		DependencyIndexes: file_ad_v1_ad_proto_depIdxs,
		MessageInfos:      file_ad_v1_ad_proto_msgTypes,
	}.Build()
	File_ad_v1_ad_proto = out.File
	file_ad_v1_ad_proto_rawDesc = nil
	file_ad_v1_ad_proto_goTypes = nil
	file_ad_v1_ad_proto_depIdxs = nil
}
